<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Item;

class ItemsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $itemsData = [
            [
                'name' => 'Sturdy Helmet',
                'hp_point' => 2,
                'damage_point' => 0,
                'shield_point' => 1,
                'luck_point' => 0,
                'intelligence_point' => 0,
                'sell_price_credit' => 50,
                'buy_price_credit' => 80,
                'buy_price_nanocrystal' => 0,
                'type' => 'Helmet',
            ],
            [
                'name' => 'Tactical Jacket',
                'hp_point' => 3,
                'damage_point' => 0,
                'shield_point' => 1,
                'luck_point' => 1,
                'intelligence_point' => 0,
                'sell_price_credit' => 60,
                'buy_price_credit' => 90,
                'buy_price_nanocrystal' => 0,
                'type' => 'Jacket',
            ],
            [
                'name' => 'Enhanced Gloves',
                'hp_point' => 1,
                'damage_point' => 0,
                'shield_point' => 0,
                'luck_point' => 1,
                'intelligence_point' => 0,
                'sell_price_credit' => 40,
                'buy_price_credit' => 60,
                'buy_price_nanocrystal' => 0,
                'type' => 'Glove',
            ],
            [
                'name' => 'Nano Boots',
                'hp_point' => 1,
                'damage_point' => 0,
                'shield_point' => 1,
                'luck_point' => 0,
                'intelligence_point' => 0,
                'sell_price_credit' => 45,
                'buy_price_credit' => 70,
                'buy_price_nanocrystal' => 0,
                'type' => 'Shoes',
            ],
            [
                'name' => 'Plasma Saber',
                'hp_point' => 0,
                'damage_point' => 9,
                'shield_point' => 0,
                'luck_point' => 0,
                'intelligence_point' => 0,
                'sell_price_credit' => 130,
                'buy_price_credit' => 190,
                'buy_price_nanocrystal' => 0,
                'type' => 'Weapon',
            ],
            [
                'name' => 'Virtual Companion',
                'hp_point' => 0,
                'damage_point' => 0,
                'shield_point' => 0,
                'luck_point' => 2,
                'intelligence_point' => 3,
                'sell_price_credit' => 70,
                'buy_price_credit' => 100,
                'buy_price_nanocrystal' => 1,
                'type' => 'Hologram',
            ],
            [
                'name' => 'Expandable Backpack',
                'hp_point' => 0,
                'damage_point' => 0,
                'shield_point' => 2,
                'luck_point' => 0,
                'intelligence_point' => 0,
                'sell_price_credit' => 55,
                'buy_price_credit' => 85,
                'buy_price_nanocrystal' => 0,
                'type' => 'Backpack',
            ],
            [
                'name' => 'Kinetic Barrier',
                'hp_point' => 0,
                'damage_point' => 0,
                'shield_point' => 4,
                'luck_point' => 0,
                'intelligence_point' => 0,
                'sell_price_credit' => 65,
                'buy_price_credit' => 95,
                'buy_price_nanocrystal' => 0,
                'type' => 'Energy Shield',
            ],
            [
                'name' => 'Lucky Mascot',
                'hp_point' => 0,
                'damage_point' => 0,
                'shield_point' => 0,
                'luck_point' => 5,
                'intelligence_point' => 1,
                'sell_price_credit' => 75,
                'buy_price_credit' => 110,
                'buy_price_nanocrystal' => 5,
                'type' => 'Mascot',
            ],
            [
                'name' => 'Techvisor',
                'hp_point' => 1,
                'damage_point' => 0,
                'shield_point' => 2,
                'luck_point' => 0,
                'intelligence_point' => 1,
                'sell_price_credit' => 60,
                'buy_price_credit' => 90,
                'buy_price_nanocrystal' => 0,
                'type' => 'Helmet',
            ],
            [
                'name' => 'Adaptive Jacket',
                'hp_point' => 2,
                'damage_point' => 0,
                'shield_point' => 2,
                'luck_point' => 1,
                'intelligence_point' => 0,
                'sell_price_credit' => 70,
                'buy_price_credit' => 100,
                'buy_price_nanocrystal' => 0,
                'type' => 'Jacket',
            ],
            [
                'name' => 'Nano Gloves',
                'hp_point' => 1,
                'damage_point' => 0,
                'shield_point' => 1,
                'luck_point' => 0,
                'intelligence_point' => 1,
                'sell_price_credit' => 50,
                'buy_price_credit' => 75,
                'buy_price_nanocrystal' => 0,
                'type' => 'Glove',
            ],
            [
                'name' => 'Stealth Boots',
                'hp_point' => 1,
                'damage_point' => 0,
                'shield_point' => 1,
                'luck_point' => 2,
                'intelligence_point' => 0,
                'sell_price_credit' => 55,
                'buy_price_credit' => 80,
                'buy_price_nanocrystal' => 0,
                'type' => 'Shoes',
            ],
            [
                'name' => 'Ion Blaster',
                'hp_point' => 0,
                'damage_point' => 7,
                'shield_point' => 1,
                'luck_point' => 0,
                'intelligence_point' => 0,
                'sell_price_credit' => 110,
                'buy_price_credit' => 160,
                'buy_price_nanocrystal' => 0,
                'type' => 'Weapon',
            ],
            [
                'name' => 'Projection Companion',
                'hp_point' => 0,
                'damage_point' => 0,
                'shield_point' => 0,
                'luck_point' => 3,
                'intelligence_point' => 2,
                'sell_price_credit' => 65,
                'buy_price_credit' => 95,
                'buy_price_nanocrystal' => 1,
                'type' => 'Hologram',
            ],
            [
                'name' => 'Storage Backpack',
                'hp_point' => 0,
                'damage_point' => 0,
                'shield_point' => 3,
                'luck_point' => 0,
                'intelligence_point' => 0,
                'sell_price_credit' => 50,
                'buy_price_credit' => 75,
                'buy_price_nanocrystal' => 0,
                'type' => 'Backpack',
            ],
            [
                'name' => 'Plasma Barrier',
                'hp_point' => 0,
                'damage_point' => 0,
                'shield_point' => 5,
                'luck_point' => 0,
                'intelligence_point' => 0,
                'sell_price_credit' => 70,
                'buy_price_credit' => 100,
                'buy_price_nanocrystal' => 0,
                'type' => 'Energy Shield',
            ],
            [
                'name' => 'Adorable Companion',
                'hp_point' => 0,
                'damage_point' => 0,
                'shield_point' => 0,
                'luck_point' => 4,
                'intelligence_point' => 1,
                'sell_price_credit' => 80,
                'buy_price_credit' => 120,
                'buy_price_nanocrystal' => 1,
                'type' => 'Mascot',
            ],
            [
                'name' => 'Deflector Helm',
                'hp_point' => 2,
                'damage_point' => 0,
                'shield_point' => 3,
                'luck_point' => 0,
                'intelligence_point' => 0,
                'sell_price_credit' => 70,
                'buy_price_credit' => 110,
                'buy_price_nanocrystal' => 0,
                'type' => 'Helmet',
            ],
            [
                'name' => 'Nano-Fiber Jacket',
                'hp_point' => 2,
                'damage_point' => 0,
                'shield_point' => 2,
                'luck_point' => 2,
                'intelligence_point' => 0,
                'sell_price_credit' => 80,
                'buy_price_credit' => 120,
                'buy_price_nanocrystal' => 0,
                'type' => 'Jacket',
            ],
            [
                'name' => 'Energized Gauntlets',
                'hp_point' => 0,
                'damage_point' => 0,
                'shield_point' => 1,
                'luck_point' => 1,
                'intelligence_point' => 2,
                'sell_price_credit' => 60,
                'buy_price_credit' => 90,
                'buy_price_nanocrystal' => 0,
                'type' => 'Glove',
            ],
            [
                'name' => 'Gravity Walkers',
                'hp_point' => 1,
                'damage_point' => 0,
                'shield_point' => 2,
                'luck_point' => 1,
                'intelligence_point' => 0,
                'sell_price_credit' => 65,
                'buy_price_credit' => 100,
                'buy_price_nanocrystal' => 0,
                'type' => 'Shoes',
            ],
            [
                'name' => 'Plasma Rifle',
                'hp_point' => 0,
                'damage_point' => 8,
                'shield_point' => 0,
                'luck_point' => 0,
                'intelligence_point' => 0,
                'sell_price_credit' => 120,
                'buy_price_credit' => 180,
                'buy_price_nanocrystal' => 0,
                'type' => 'Weapon',
            ],
            [
                'name' => 'Interactive AI',
                'hp_point' => 0,
                'damage_point' => 0,
                'shield_point' => 0,
                'luck_point' => 3,
                'intelligence_point' => 3,
                'sell_price_credit' => 75,
                'buy_price_credit' => 110,
                'buy_price_nanocrystal' => 2,
                'type' => 'Hologram',
            ],
            [
                'name' => 'Advanced Rucksack',
                'hp_point' => 0,
                'damage_point' => 0,
                'shield_point' => 4,
                'luck_point' => 0,
                'intelligence_point' => 0,
                'sell_price_credit' => 60,
                'buy_price_credit' => 90,
                'buy_price_nanocrystal' => 0,
                'type' => 'Backpack',
            ],
            [
                'name' => 'Photon Barrier',
                'hp_point' => 0,
                'damage_point' => 0,
                'shield_point' => 6,
                'luck_point' => 0,
                'intelligence_point' => 0,
                'sell_price_credit' => 80,
                'buy_price_credit' => 120,
                'buy_price_nanocrystal' => 0,
                'type' => 'Energy Shield',
            ],
            [
                'name' => 'Galactic Pet',
                'hp_point' => 0,
                'damage_point' => 0,
                'shield_point' => 0,
                'luck_point' => 5,
                'intelligence_point' => 2,
                'sell_price_credit' => 90,
                'buy_price_credit' => 130,
                'buy_price_nanocrystal' => 1,
                'type' => 'Mascot',
            ],
            [
                'name' => 'Quantum Helmet',
                'hp_point' => 3,
                'damage_point' => 0,
                'shield_point' => 4,
                'luck_point' => 0,
                'intelligence_point' => 0,
                'sell_price_credit' => 90,
                'buy_price_credit' => 130,
                'buy_price_nanocrystal' => 0,
                'type' => 'Helmet',
            ],
            [
                'name' => 'Adaptive Nano-Jacket',
                'hp_point' => 3,
                'damage_point' => 0,
                'shield_point' => 3,
                'luck_point' => 2,
                'intelligence_point' => 0,
                'sell_price_credit' => 100,
                'buy_price_credit' => 150,
                'buy_price_nanocrystal' => 0,
                'type' => 'Jacket',
            ],
            [
                'name' => 'Nanite Gauntlets',
                'hp_point' => 0,
                'damage_point' => 0,
                'shield_point' => 2,
                'luck_point' => 1,
                'intelligence_point' => 3,
                'sell_price_credit' => 70,
                'buy_price_credit' => 100,
                'buy_price_nanocrystal' => 0,
                'type' => 'Glove',
            ],
            [
                'name' => 'Stealthy Striders',
                'hp_point' => 2,
                'damage_point' => 0,
                'shield_point' => 3,
                'luck_point' => 2,
                'intelligence_point' => 0,
                'sell_price_credit' => 75,
                'buy_price_credit' => 110,
                'buy_price_nanocrystal' => 0,
                'type' => 'Shoes',
            ],
            [
                'name' => 'Ionized Blaster',
                'hp_point' => 0,
                'damage_point' => 6,
                'shield_point' => 1,
                'luck_point' => 0,
                'intelligence_point' => 0,
                'sell_price_credit' => 100,
                'buy_price_credit' => 150,
                'buy_price_nanocrystal' => 0,
                'type' => 'Weapon',
            ],
            [
                'name' => 'Holo-Companion',
                'hp_point' => 0,
                'damage_point' => 0,
                'shield_point' => 0,
                'luck_point' => 4,
                'intelligence_point' => 4,
                'sell_price_credit' => 85,
                'buy_price_credit' => 120,
                'buy_price_nanocrystal' => 1,
                'type' => 'Hologram',
            ],
            [
                'name' => 'Quantum Storage Pack',
                'hp_point' => 0,
                'damage_point' => 0,
                'shield_point' => 5,
                'luck_point' => 0,
                'intelligence_point' => 0,
                'sell_price_credit' => 70,
                'buy_price_credit' => 100,
                'buy_price_nanocrystal' => 0,
                'type' => 'Backpack',
            ],
            [
                'name' => 'Quantum Shield',
                'hp_point' => 0,
                'damage_point' => 0,
                'shield_point' => 7,
                'luck_point' => 0,
                'intelligence_point' => 0,
                'sell_price_credit' => 90,
                'buy_price_credit' => 130,
                'buy_price_nanocrystal' => 0,
                'type' => 'Energy Shield',
            ],
            [
                'name' => 'Astro Buddy',
                'hp_point' => 0,
                'damage_point' => 0,
                'shield_point' => 0,
                'luck_point' => 6,
                'intelligence_point' => 3,
                'sell_price_credit' => 100,
                'buy_price_credit' => 140,
                'buy_price_nanocrystal' => 1,
                'type' => 'Mascot',
            ],
            [
                'name' => 'Nanotech Helmet Mk II',
                'hp_point' => 5,
                'damage_point' => 0,
                'shield_point' => 8,
                'luck_point' => 0,
                'intelligence_point' => 2,
                'sell_price_credit' => 250,
                'buy_price_credit' => 400,
                'buy_price_nanocrystal' => 0,
                'type' => 'Helmet',
            ],
            [
                'name' => 'Energy-Woven Jacket',
                'hp_point' => 6,
                'damage_point' => 0,
                'shield_point' => 6,
                'luck_point' => 3,
                'intelligence_point' => 0,
                'sell_price_credit' => 300,
                'buy_price_credit' => 450,
                'buy_price_nanocrystal' => 0,
                'type' => 'Jacket',
            ],
            [
                'name' => 'Plasma Gauntlets',
                'hp_point' => 0,
                'damage_point' => 0,
                'shield_point' => 4,
                'luck_point' => 2,
                'intelligence_point' => 4,
                'sell_price_credit' => 220,
                'buy_price_credit' => 350,
                'buy_price_nanocrystal' => 0,
                'type' => 'Glove',
            ],
            [
                'name' => 'Quantum Striders',
                'hp_point' => 4,
                'damage_point' => 0,
                'shield_point' => 6,
                'luck_point' => 3,
                'intelligence_point' => 0,
                'sell_price_credit' => 240,
                'buy_price_credit' => 380,
                'buy_price_nanocrystal' => 0,
                'type' => 'Shoes',
            ],
            [
                'name' => 'Plasma Cannon',
                'hp_point' => 0,
                'damage_point' => 14,
                'shield_point' => 0,
                'luck_point' => 0,
                'intelligence_point' => 0,
                'sell_price_credit' => 350,
                'buy_price_credit' => 500,
                'buy_price_nanocrystal' => 0,
                'type' => 'Weapon',
            ],
            [
                'name' => 'Holo-Companion 9000',
                'hp_point' => 0,
                'damage_point' => 0,
                'shield_point' => 0,
                'luck_point' => 8,
                'intelligence_point' => 6,
                'sell_price_credit' => 300,
                'buy_price_credit' => 450,
                'buy_price_nanocrystal' => 1,
                'type' => 'Hologram',
            ],
            [
                'name' => 'Dimensional Backpack',
                'hp_point' => 0,
                'damage_point' => 0,
                'shield_point' => 8,
                'luck_point' => 0,
                'intelligence_point' => 0,
                'sell_price_credit' => 280,
                'buy_price_credit' => 420,
                'buy_price_nanocrystal' => 0,
                'type' => 'Backpack',
            ],
            [
                'name' => 'Plasma Deflector',
                'hp_point' => 0,
                'damage_point' => 0,
                'shield_point' => 12,
                'luck_point' => 0,
                'intelligence_point' => 0,
                'sell_price_credit' => 320,
                'buy_price_credit' => 480,
                'buy_price_nanocrystal' => 0,
                'type' => 'Energy Shield',
            ],
            [
                'name' => 'Quantum Familiar',
                'hp_point' => 0,
                'damage_point' => 0,
                'shield_point' => 0,
                'luck_point' => 10,
                'intelligence_point' => 5,
                'sell_price_credit' => 350,
                'buy_price_credit' => 500,
                'buy_price_nanocrystal' => 5,
                'type' => 'Mascot',
            ],
            [
                'name' => 'Nanotech Helmet Mk III',
                'hp_point' => 7,
                'damage_point' => 0,
                'shield_point' => 10,
                'luck_point' => 0,
                'intelligence_point' => 3,
                'sell_price_credit' => 350,
                'buy_price_credit' => 550,
                'buy_price_nanocrystal' => 0,
                'type' => 'Helmet',
            ],
            [
                'name' => 'Quantum Energy Jacket',
                'hp_point' => 8,
                'damage_point' => 0,
                'shield_point' => 8,
                'luck_point' => 4,
                'intelligence_point' => 0,
                'sell_price_credit' => 400,
                'buy_price_credit' => 600,
                'buy_price_nanocrystal' => 0,
                'type' => 'Jacket',
            ],
            [
                'name' => 'Fusion Gauntlets',
                'hp_point' => 0,
                'damage_point' => 0,
                'shield_point' => 6,
                'luck_point' => 3,
                'intelligence_point' => 5,
                'sell_price_credit' => 300,
                'buy_price_credit' => 500,
                'buy_price_nanocrystal' => 0,
                'type' => 'Glove',
            ],
            [
                'name' => 'Dimensional Striders',
                'hp_point' => 6,
                'damage_point' => 0,
                'shield_point' => 8,
                'luck_point' => 4,
                'intelligence_point' => 0,
                'sell_price_credit' => 320,
                'buy_price_credit' => 520,
                'buy_price_nanocrystal' => 0,
                'type' => 'Shoes',
            ],
            [
                'name' => 'Quantum Plasma Blaster',
                'hp_point' => 0,
                'damage_point' => 18,
                'shield_point' => 0,
                'luck_point' => 0,
                'intelligence_point' => 0,
                'sell_price_credit' => 450,
                'buy_price_credit' => 650,
                'buy_price_nanocrystal' => 0,
                'type' => 'Weapon',
            ],
            [
                'name' => 'Holo-Companion Elite',
                'hp_point' => 0,
                'damage_point' => 0,
                'shield_point' => 0,
                'luck_point' => 10,
                'intelligence_point' => 8,
                'sell_price_credit' => 400,
                'buy_price_credit' => 600,
                'buy_price_nanocrystal' => 1,
                'type' => 'Hologram',
            ],
            [
                'name' => 'Quantum Storage Nexus',
                'hp_point' => 0,
                'damage_point' => 0,
                'shield_point' => 10,
                'luck_point' => 0,
                'intelligence_point' => 0,
                'sell_price_credit' => 380,
                'buy_price_credit' => 580,
                'buy_price_nanocrystal' => 0,
                'type' => 'Backpack',
            ],
            [
                'name' => 'Hyper Plasma Shield',
                'hp_point' => 0,
                'damage_point' => 0,
                'shield_point' => 15,
                'luck_point' => 0,
                'intelligence_point' => 0,
                'sell_price_credit' => 420,
                'buy_price_credit' => 620,
                'buy_price_nanocrystal' => 0,
                'type' => 'Energy Shield',
            ],
            [
                'name' => 'Cosmic Companion',
                'hp_point' => 0,
                'damage_point' => 0,
                'shield_point' => 0,
                'luck_point' => 12,
                'intelligence_point' => 7,
                'sell_price_credit' => 450,
                'buy_price_credit' => 650,
                'buy_price_nanocrystal' => 1,
                'type' => 'Mascot',
            ],
        ];

        foreach ($itemsData as $itemData) {
            Item::create($itemData);
        }
    }
}
