<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Mission;


class MissionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $missionsData = [
            [
                'name' => 'Scrapbot Scuffle',
                'description' => 'Clear out a group of Scrapbots that have been causing trouble in the area.',
                'monster_id' => 11,
                'credit_reward' => 50,
                'xp_reward' => 100,
                'seconds' => 12,
                'nanocrystal_chance_reward' => 10,
                'difficulty' => 'Easy',
                'mission_type' => 'Battle',
                'required_level' => 1,
                'image_path' => 'scrapbot_scuffle.png',
                'reward_item_id' => 9,
            ],
            [
                'name' => 'Jellybit Infestation',
                'description' => 'Exterminate a swarm of Jellybits that have invaded a local settlement.',
                'monster_id' => 12,
                'credit_reward' => 60,
                'xp_reward' => 110,
                'seconds' => 15,
                'nanocrystal_chance_reward' => 5,
                'difficulty' => 'Easy',
                'mission_type' => 'Battle',
                'required_level' => 1,
                'image_path' => 'jellybit_infestation.png',
                'reward_item_id' => 20,
            ],
            [
                'name' => 'Zapbug Hunt',
                'description' => 'Track down and eliminate a nest of Zapbugs before they cause more damage.',
                'monster_id' => 13,
                'credit_reward' => 70,
                'xp_reward' => 120,
                'seconds' => 18,
                'nanocrystal_chance_reward' => 5,
                'difficulty' => 'Easy',
                'mission_type' => 'Battle',
                'required_level' => 2,
                'image_path' => 'zapbug_hunt.png',
                'reward_item_id' => 14,
            ],
            [
                'name' => 'Laserbat Menace',
                'description' => 'Deal with a group of Laserbats that have been terrorizing the local wildlife.',
                'monster_id' => 14,
                'credit_reward' => 80,
                'xp_reward' => 130,
                'seconds' => 20,
                'nanocrystal_chance_reward' => 5,
                'difficulty' => 'Easy',
                'mission_type' => 'Battle',
                'required_level' => 2,
                'image_path' => 'laserbat_menace.png',
                'reward_item_id' => null,
            ],
            [
                'name' => 'Gooey Blob Outbreak',
                'description' => 'Contain and neutralize a sudden outbreak of Gooey Blobs in a research facility.',
                'monster_id' => 15,
                'credit_reward' => 90,
                'xp_reward' => 140,
                'seconds' => 240,
                'nanocrystal_chance_reward' => 10,
                'difficulty' => 'Easy',
                'mission_type' => 'Battle',
                'required_level' => 3,
                'image_path' => 'gooey_blob_outbreak.png',
                'reward_item_id' => null,
            ],
            [
                'name' => 'Plasma Sprite Invasion',
                'description' => 'Repel an invasion of Plasma Sprites that threaten to disrupt communications.',
                'monster_id' => 16,
                'credit_reward' => 100,
                'xp_reward' => 150,
                'seconds' => 240,
                'nanocrystal_chance_reward' => 15,
                'difficulty' => 'Moderate',
                'mission_type' => 'Battle',
                'required_level' => 3,
                'image_path' => 'plasma_sprite_invasion.png',
                'reward_item_id' => null,
            ],
            [
                'name' => 'Circuit Critter Menace',
                'description' => 'Deal with a swarm of Circuit Critters causing malfunctions in a robotics lab.',
                'monster_id' => 17,
                'credit_reward' => 110,
                'xp_reward' => 160,
                'seconds' => 260,
                'nanocrystal_chance_reward' => 10,
                'difficulty' => 'Moderate',
                'mission_type' => 'Battle',
                'required_level' => 4,
                'image_path' => 'circuit_critter_menace.png',
                'reward_item_id' => null,
            ],
            [
                'name' => 'Glowing Mite Nest',
                'description' => 'Eradicate a nest of Glowing Mites that have infested an underground facility.',
                'monster_id' => 18,
                'credit_reward' => 120,
                'xp_reward' => 170,
                'seconds' => 280,
                'nanocrystal_chance_reward' => 10,
                'difficulty' => 'Moderate',
                'mission_type' => 'Battle',
                'required_level' => 4,
                'image_path' => 'glowing_mite_nest.png',
                'reward_item_id' => null,
            ],
            [
                'name' => 'Neon Nibbler Infestation',
                'description' => 'Protect a scientific outpost from a relentless Neon Nibbler swarm.',
                'monster_id' => 19,
                'credit_reward' => 130,
                'xp_reward' => 180,
                'seconds' => 300,
                'nanocrystal_chance_reward' => 15,
                'difficulty' => 'Moderate',
                'mission_type' => 'Battle',
                'required_level' => 5,
                'image_path' => 'neon_nibbler_infestation.png',
                'reward_item_id' => null,
            ],
            [
                'name' => 'Pyro Pixie Rampage',
                'description' => 'Contain a Pyro Pixie that has gone on a destructive rampage in a forest.',
                'monster_id' => 20,
                'credit_reward' => 140,
                'xp_reward' => 190,
                'seconds' => 320,
                'nanocrystal_chance_reward' => 20,
                'difficulty' => 'Moderate',
                'mission_type' => 'Battle',
                'required_level' => 5,
                'image_path' => 'pyro_pixie_rampage.png',
                'reward_item_id' => null,
            ],
            [
                'name' => 'Cyber Serpent Showdown',
                'description' => 'Engage in a fierce battle against a menacing Cyber Serpent in a digital realm.',
                'monster_id' => 21,
                'credit_reward' => 150,
                'xp_reward' => 200,
                'seconds' => 360,
                'nanocrystal_chance_reward' => 20,
                'difficulty' => 'Challenging',
                'mission_type' => 'Battle',
                'required_level' => 6,
                'image_path' => 'cyber_serpent_showdown.png',
                'reward_item_id' => null,
            ],
            [
                'name' => 'Plasma Golem Rampage',
                'description' => 'Stop a Plasma Golem that is causing destruction in a highly populated city.',
                'monster_id' => 22,
                'credit_reward' => 160,
                'xp_reward' => 210,
                'seconds' => 380,
                'nanocrystal_chance_reward' => 15,
                'difficulty' => 'Challenging',
                'mission_type' => 'Battle',
                'required_level' => 6,
                'image_path' => 'plasma_golem_rampage.png',
                'reward_item_id' => null,
            ],
            [
                'name' => 'Ion Behemoth Assault',
                'description' => 'Lead a team to take down the colossal Ion Behemoth before it reaches a populated area.',
                'monster_id' => 23,
                'credit_reward' => 170,
                'xp_reward' => 220,
                'seconds' => 400,
                'nanocrystal_chance_reward' => 10,
                'difficulty' => 'Challenging',
                'mission_type' => 'Battle',
                'required_level' => 7,
                'image_path' => 'ion_behemoth_assault.png',
                'reward_item_id' => null,
            ],
            [
                'name' => 'Nanite Harbinger Menace',
                'description' => 'Face the chaotic Nanite Harbinger in a high-stakes battle to prevent a global catastrophe.',
                'monster_id' => 24,
                'credit_reward' => 180,
                'xp_reward' => 230,
                'seconds' => 420,
                'nanocrystal_chance_reward' => 25,
                'difficulty' => 'Challenging',
                'mission_type' => 'Battle',
                'required_level' => 7,
                'image_path' => 'nanite_harbinger_menace.png',
                'reward_item_id' => null,
            ],
            [
                'name' => 'Neural Fiend`s Mind Games',
                'description' => 'Confront the Neural Fiend in a battle of wits and outsmart its mental illusions.',
                'monster_id' => 25,
                'credit_reward' => 190,
                'xp_reward' => 240,
                'seconds' => 440,
                'nanocrystal_chance_reward' => 30,
                'difficulty' => 'Challenging',
                'mission_type' => 'Battle',
                'required_level' => 8,
                'image_path' => 'neural_fiend_mind_games.png',
                'reward_item_id' => null,
            ],
        ];

        foreach ($missionsData as $missionData) {
            Mission::create($missionData);
        }

    }
}
