<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Monster;

class MonstersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $monstersData = [
            [
                'name' => 'Microdrone',
                'description' => 'A minuscule drone armed with a tiny laser.',
                'image_path' => 'microdrone.png',
                'hp' => 15,
                'damage' => 3,
                'luck' => 1,
                'level' => 15,
                'integrity' => 15,
                'intelligence' => 0,
                'shield' => 0,
            ],
            [
                'name' => 'Jellybit',
                'description' => 'A small, gelatinous creature that wobbles around.',
                'image_path' => 'jellybit.png',
                'hp' => 10,
                'damage' => 2,
                'luck' => 1,
                'level' => 10,
                'integrity' => 10,
                'intelligence' => 0,
                'shield' => 0,
            ],
            [
                'name' => 'Sparklerat',
                'description' => 'A rodent-like creature that occasionally emits sparks.',
                'image_path' => 'sparklerat.png',
                'hp' => 12,
                'damage' => 1,
                'luck' => 1,
                'level' => 12,
                'integrity' => 12,
                'intelligence' => 0,
                'shield' => 0,
            ],
            [
                'name' => 'Laserroach',
                'description' => 'A cockroach infused with laser technology.',
                'image_path' => 'laserroach.png',
                'hp' => 8,
                'damage' => 2,
                'luck' => 1,
                'level' => 8,
                'integrity' => 8,
                'intelligence' => 0,
                'shield' => 0,
            ],
            [
                'name' => 'Nanoslime',
                'description' => 'A microscopic slime that can merge and divide.',
                'image_path' => 'nanoslime.png',
                'hp' => 6,
                'damage' => 1,
                'luck' => 2,
                'level' => 6,
                'integrity' => 6,
                'intelligence' => 0,
                'shield' => 0,
            ],
            [
                'name' => 'Plasma Sprite',
                'description' => 'A small energy being that emits weak plasma bursts.',
                'image_path' => 'plasma_sprite.png',
                'hp' => 18,
                'damage' => 4,
                'luck' => 2,
                'level' => 18,
                'integrity' => 18,
                'intelligence' => 0,
                'shield' => 0,
            ],
            [
                'name' => 'Circuit Critter',
                'description' => 'A tiny creature made of living circuits that delivers electric shocks.',
                'image_path' => 'circuit_critter.png',
                'hp' => 14,
                'damage' => 3,
                'luck' => 2,
                'level' => 14,
                'integrity' => 14,
                'intelligence' => 0,
                'shield' => 0,
            ],
            [
                'name' => 'Glowing Mite',
                'description' => 'A luminescent insect-like being that emits a dim light.',
                'image_path' => 'glowing_mite.png',
                'hp' => 9,
                'damage' => 1,
                'luck' => 3,
                'level' => 9,
                'integrity' => 9,
                'intelligence' => 0,
                'shield' => 0,
            ],
            [
                'name' => 'Neon Nibbler',
                'description' => 'A small, colorful creature with sharp teeth, dealing small bites.',
                'image_path' => 'neon_nibbler.png',
                'hp' => 10,
                'damage' => 2,
                'luck' => 2,
                'level' => 10,
                'integrity' => 10,
                'intelligence' => 0,
                'shield' => 0,
            ],
            [
                'name' => 'Pyro Pixie',
                'description' => 'A fiery sprite that leaves a trail of sparks behind.',
                'image_path' => 'pyro_pixie.png',
                'hp' => 16,
                'damage' => 3,
                'luck' => 1,
                'level' => 16,
                'integrity' => 16,
                'intelligence' => 0,
                'shield' => 0,
            ],
            [
                'name' => 'Plasma Pup',
                'description' => 'A small floating creature that playfully shoots plasma bolts.',
                'image_path' => 'plasma_pup.png',
                'hp' => 12,
                'damage' => 2,
                'luck' => 2,
                'level' => 12,
                'integrity' => 12,
                'intelligence' => 0,
                'shield' => 0,
            ],
            [
                'name' => 'Metallic Moth',
                'description' => 'A mechanical moth that flutters around and has minor defensive capabilities.',
                'image_path' => 'metallic_moth.png',
                'hp' => 8,
                'damage' => 1,
                'luck' => 1,
                'level' => 8,
                'integrity' => 8,
                'intelligence' => 0,
                'shield' => 0,
            ],
            [
                'name' => 'Nebula Nymph',
                'description' => 'A tiny nymph-like being made of stardust, dealing weak stardust attacks.',
                'image_path' => 'nebula_nymph.png',
                'hp' => 10,
                'damage' => 2,
                'luck' => 3,
                'level' => 10,
                'integrity' => 10,
                'intelligence' => 0,
                'shield' => 0,
            ],
            [
                'name' => 'Pixel Parasite',
                'description' => 'A digital parasite that glitches in and out of reality, delivering electric shocks.',
                'image_path' => 'pixel_parasite.png',
                'hp' => 14,
                'damage' => 3,
                'luck' => 1,
                'level' => 14,
                'integrity' => 14,
                'intelligence' => 0,
                'shield' => 0,
            ],
            [
                'name' => 'Steam Sprite',
                'description' => 'A steam-emitting creature that leaves behind misty trails.',
                'image_path' => 'steam_sprite.png',
                'hp' => 16,
                'damage' => 2,
                'luck' => 2,
                'level' => 16,
                'integrity' => 16,
                'intelligence' => 0,
                'shield' => 0,
            ],
            [
                'name' => 'Plasma Elemental',
                'description' => 'A small elemental creature composed of swirling plasma, delivering powerful plasma blasts.',
                'image_path' => 'plasma_elemental.png',
                'hp' => 25,
                'damage' => 6,
                'luck' => 2,
                'level' => 25,
                'integrity' => 25,
                'intelligence' => 0,
                'shield' => 0,
            ],
            [
                'name' => 'Cyber Serpent',
                'description' => 'A robotic serpent with sharp mechanical fangs and powerful strikes.',
                'image_path' => 'cyber_serpent.png',
                'hp' => 30,
                'damage' => 8,
                'luck' => 3,
                'level' => 30,
                'integrity' => 30,
                'intelligence' => 0,
                'shield' => 0,
            ],
            [
                'name' => 'Plasma Golem',
                'description' => 'A humanoid creature made of solidified plasma, delivering devastating plasma strikes.',
                'image_path' => 'plasma_golem.png',
                'hp' => 40,
                'damage' => 10,
                'luck' => 1,
                'level' => 40,
                'integrity' => 40,
                'intelligence' => 0,
                'shield' => 0,
            ],
            [
                'name' => 'Ion Behemoth',
                'description' => 'A massive beast that emits electromagnetic pulses, dealing powerful shocks.',
                'image_path' => 'ion_behemoth.png',
                'hp' => 50,
                'damage' => 12,
                'luck' => 2,
                'level' => 50,
                'integrity' => 50,
                'intelligence' => 0,
                'shield' => 0,
            ],
            [
                'name' => 'Nanite Harbinger',
                'description' => 'A humanoid figure composed of swarming nanobots, capable of delivering powerful nanobot strikes.',
                'image_path' => 'nanite_harbinger.png',
                'hp' => 35,
                'damage' => 9,
                'luck' => 4,
                'level' => 35,
                'integrity' => 35,
                'intelligence' => 0,
                'shield' => 0,
            ],
            [
                'name' => 'Neural Fiend',
                'description' => 'A creature with psychic abilities, able to manipulate thoughts and reality.',
                'image_path' => 'neural_fiend.png',
                'hp' => 45,
                'damage' => 11,
                'luck' => 5,
                'level' => 45,
                'integrity' => 45,
                'intelligence' => 0,
                'shield' => 0,
            ],
        ];

        foreach ($monstersData as $monsterData) {
            Monster::create($monsterData);
        }
    
    }
}
